#define TCP_SILENT_FAIL_TEST_INTERVAL 120
#define MAX_ERROR_SLEEP 12

#define MAX_IDLE_TIME 303

#define DEFAULT_BROKER_PORT 55225

#define DEFAULT_PROXY_LISTEN_PORT 12347

#define DEFAULT_COMM_TO 15

// data logger
#define MEASURE_INTERVAL 300
#define MEASURE_KEEP_N	((86400 / MEASURE_INTERVAL) * 7)
