.TH EB_CLIENT_EGD "1" "July 2012" "eb_client_egd" "User Commands"
.SH NAME
eb_client_egd \- export entropy data as egd server
.SH DESCRIPTION
eb_client_egd v1.0, (C) 2009-2012 by folkert@vanheusden.com
Egd-clients can use the /tmp/egd.sock unix domain socket. This should work with at least OpenSSL: start eb_client_egd with one of the following parameters: \-d /var/run/egd-pool or \-d /dev/egd-pool or \-d /etc/egd-pool or \-d /etc/entropy To verify that client_egd functions, run: "openssl rand \-rand /var/run/egd-pool \-out /tmp/bla 10".  It should return something like "255 semi-random bytes loaded" where "255" should be > 0. If it is zero, check if the current user has enough rights to access the /var/run/egd-pool file.
.TP
\fB\-i\fR host   eb\-host to connect to
.TP
\fB\-d\fR file   UNIX-domain socket to listen on
.TP
\fB\-l\fR file   log to file 'file'
.TP
\fB\-s\fR        log to syslog
.TP
\fB\-n\fR        do not fork
.TP
\fB\-P\fR file   file to write the PID to
.TP
\fB\-X\fR file   file to read the password from
