.TH EB_CLIENT_LINUX_KERNEL "1" "July 2012" "eb_client_linux_kernel" "User Commands"
.SH NAME
eb_client_linux_kernel \- send entropy data to /dev/random
.SH DESCRIPTION
eb_client_linux_kernel v0.9.1, (C) 2009-2012 by folkert@vanheusden.com
.TP
\fB\-i\fR host   eb\-host to connect to
.TP
\fB\-d\fR file   unix domain socket
.TP
\fB\-l\fR file   log to file 'file'
.TP
\fB\-s\fR        log to syslog
.TP
\fB\-n\fR        do not fork
