.TH EB_CLIENT_EGD "1" "July 2012" "eb_client_egd" "User Commands"
.SH NAME
eb_client_file \- export entropy data to a file
.SH DESCRIPTION
eb_client_file v1.0, (C) 2009-2012 by folkert@vanheusden.com
.TP
\fB\-i\fR host   eb\-host to connect to
.TP
\fB\-f\fR file   file to write to
.TP
\fB\-c\fR count  number of bytes to write
.TP
\fB\-l\fR file   log to file 'file'
.TP
\fB\-s\fR        log to syslog
.TP
\fB\-n\fR        do not fork
.TP
\fB\-P\fR file   file to write the PID to
.TP
\fB\-X\fR file   file to read the password from
