.TH EB_CLIENT_EGD "1" "July 2012" "eb_client_egd" "User Commands"
.SH NAME
eb_client_egd \- export entropy data as egd server
.SH DESCRIPTION
eb_client_egd v0.9.1, (C) 2009-2012 by folkert@vanheusden.com
.TP
\fB\-i\fR host   eb\-host to connect to
.TP
\fB\-l\fR file   log to file 'file'
.TP
\fB\-s\fR        log to syslog
.TP
\fB\-n\fR        do not fork
