.TH EB_SERVER_TIMERS "1" "July 2012" "eb_server_timers" "User Commands"
.SH NAME
eb_server_timers \- gather entropy on systems that are mostly idle
.SH DESCRIPTION
.TP
\fB\-i\fR host   eb\-host to connect to
.TP
\fB\-o\fR file   file to write entropy data to
.TP
\fB\-l\fR file   log to file 'file'
.TP
\fB\-s\fR        log to syslog
.TP
\fB\-n\fR        do not fork
