.TH EB_SERVER_TIMERS "1" "July 2012" "eb_server_timers" "User Commands"
.SH NAME
eb_server_timers \- gather entropy on systems that are mostly idle
.SH DESCRIPTION
eb_server_timers v1.0, (C) 2009-2012 by folkert@vanheusden.com
.TP
\fB\-i\fR host   eb\-host to connect to
.TP
\fB\-l\fR file   log to file 'file'
.TP
\fB\-s\fR        log to syslog
.TP
\fB\-n\fR        do not fork
.TP
\fB\-P\fR file   file to write the PID to
.TP
\fB\-X\fR file   file to read the password from
