.TH ENTROPY_BROKER "1" "July 2012" "entropy_broker" "User Commands"
.SH NAME
entropy_broker \- server to gather entropy data from different clients
.SH DESCRIPTION
entropy_broker v1.0, (C) 2009-2012 by folkert@vanheusden.com
.TP
\fB\-c\fR file   config\-file to read
.TP
\fB\-l\fR file   log to file 'file'
.TP
\fB\-s\fR        log to syslog
.TP
\fB\-S\fR        statistics\-file to log to
.TP
\fB\-n\fR        do not fork
.TP
\fB\-P\fR file   file to write the PID to
