#!/bin/sh
#
# eb_client_linux_kernel - Entropy broker linux kernel client
# SVN: $Revision$
#
# chkconfig:   2345 28 83
# description: This daemon installs brokered entropy into the linux kernel
#
# processname: eb_client_linux_kernel
# pidfile: /usr/local/entropybroker/var/run/client_linux_kernel.pid

### BEGIN INIT INFO
# Provides: eb_client_linux_kernel
# Required-Start:
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop linux kernel entropy client
# Description: eb_client_linux_kernel is a daemon for installing brokered entropy into the kernel.
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

exec="/usr/local/entropybroker/bin/eb_client_linux_kernel"
prog=$(basename $exec)

KERNEL_WAKE_THRESHOLD=512

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

lockfile=/var/lock/subsys/$prog

start() {
    echo -n $"Starting $prog: "

    echo "$KERNEL_WAKE_THRESHOLD" >/proc/sys/kernel/random/write_wakeup_threshold

    $exec $OPTIONS
    retval=$?
    [ $retval -ne 0 ] && failure
    [ $retval -eq 0 ] && success && touch $lockfile
    echo
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

case "$1" in
    start|stop|restart)
        $1
        ;;
    force-reload)
        restart
        ;;
    status)
        status $prog
        ;;
    try-restart|condrestart)
        if status $prog >/dev/null ; then
            restart
        fi
        ;;
    reload)
        # If config can be reloaded without restarting, implement it here,
        # remove the "exit", and add "reload" to the usage message below.
        # For example:
        # status $prog >/dev/null || exit 7
        killproc $prog -HUP
        #action $"Service ${0##*/} does not support the reload action: " /bin/false
        exit 3
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|try-restart|force-reload}"
        exit 2
esac

