#!/bin/sh
#
# eb_server_ComScire_R2000KU - Entropy broker egd source 
#
# chkconfig:   2345 27 84
# description: This daemon manages entropy sources and distributes entropy
# 	       to clients.
#
# processname: eb_server_ComScire_R2000KU
# pidfile: /usr/local/entropybroker/var/run/server_ComScire_R2000KU.pid

### BEGIN INIT INFO
# Provides: eb_server_ComScire_R2000KU
# Required-Start:
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop egd entropy server
# Description: eb_server_ComScire_R2000KU is a daemon for collecting entropy from EGD.
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

exec="/usr/local/entropybroker/bin/eb_server_ComScire_R2000KU"
prog=$(basename $exec)

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

lockfile=/var/lock/subsys/$prog

start() {
    echo -n $"Starting $prog: "

    $exec $OPTIONS
    retval=$?
    [ $retval -ne 0 ] && failure
    [ $retval -eq 0 ] && success && touch $lockfile
    echo
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

case "$1" in
    start|stop|restart)
        $1
        ;;
    force-reload)
        restart
        ;;
    status)
        status $prog
        ;;
    try-restart|condrestart)
        if status $prog >/dev/null ; then
            restart
        fi
        ;;
    reload)
        # If config can be reloaded without restarting, implement it here,
        # remove the "exit", and add "reload" to the usage message below.
        # For example:
        # status $prog >/dev/null || exit 7
        killproc $prog -HUP
        #action $"Service ${0##*/} does not support the reload action: " /bin/false
        exit 3
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|try-restart|force-reload}"
        exit 2
esac

